apiVersion: v1
kind: Service
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
    service.beta.openshift.io/serving-cert-secret-name: compatibility-requirements-controllers-webhook-service-cert
  name: compatibility-requirements-controllers-webhook-service
  namespace: openshift-compatibility-requirements-operator
spec:
  ports:
  - name: compatibility-requirements-controllers-webhook-server
    port: 443
    targetPort: webhook-server
  selector:
    k8s-app: compatibility-requirements-controllers
  type: ClusterIP
  sessionAffinity: None
