---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-compatibility-requirements-operator
  name: compatibility-requirements-controllers
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
---
apiVersion: v1
kind: Secret
metadata:
  name: compatibility-requirements-controllers-token
  namespace: openshift-compatibility-requirements-operator
  annotations:
    kubernetes.io/service-account.name: compatibility-requirements-controllers
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
type: kubernetes.io/service-account-token
