apiVersion: v1
data:
  providers-list.yaml: |+
    - name: cluster-api
      type: CoreProvider
      branch: release-4.14
      version: v1.4.2
    - name: aws
      type: InfrastructureProvider
      branch: openshift-fix-subnet-creation
      version: v2.2.0
      org: JoelSpeed
    - name: azure
      type: InfrastructureProvider
      branch: release-4.14
      version: v1.9.5
    - name: gcp
      type: InfrastructureProvider
      branch: master
      version: v1.4.0
    - name: powervs
      type: InfrastructureProvider
      branch: release-4.14
      version: v0.5.1

kind: ConfigMap
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  creationTimestamp: null
  name: cluster-capi-operator-providers
  namespace: openshift-cluster-api
