apiVersion: v1
data:
  providers-list.yaml: |+
    - name: cluster-api
      type: CoreProvider
      branch: release-4.14
      version: v1.3.3
    - name: aws
      type: InfrastructureProvider
      branch: release-4.14
      version: v2.0.2
    - name: azure
      type: InfrastructureProvider
      branch: release-4.14
      version: v1.7.1
    - name: gcp
      type: InfrastructureProvider
      branch: release-4.14
      version: v1.2.1
    - name: powervs
      type: InfrastructureProvider
      branch: release-4.14
      version: v0.3.0

kind: ConfigMap
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  creationTimestamp: null
  name: cluster-capi-operator-providers
  namespace: openshift-cluster-api
