---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-compatibility-requirements
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: "CustomNoUpgrade,TechPreviewNoUpgrade"
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: crd-compatibility-checker-webhook-service
      namespace: openshift-cluster-api
      path: /validate-apiextensions-k8s-io-v1-customresourcedefinition
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: compatibilityrequirement.operator.openshift.io
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - customresourcedefinitions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-compatibility-controller
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: "CustomNoUpgrade,TechPreviewNoUpgrade"
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: crd-compatibility-checker-webhook-service
      namespace: openshift-cluster-api
      path: /validate-apiextensions-openshift-io-v1alpha1-compatibilityrequirement
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: compatibilityrequirement.operator.openshift.io
  rules:
  - apiGroups:
    - apiextensions.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - compatibilityrequirements
  sideEffects: None
