---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-compatibility-requirements-operator:compatibility-requirements-controllers
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
roleRef:
  kind: ClusterRole
  name: system:openshift:openshift-compatibility-requirements-operator:compatibility-requirements-controllers
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-compatibility-requirements-operator
  name: compatibility-requirements-controllers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compatibility-requirements-controllers
  namespace: openshift-compatibility-requirements-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
roleRef:
  kind: Role
  name: compatibility-requirements-controllers
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-compatibility-requirements-operator
  name: compatibility-requirements-controllers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:compatibility-requirements-events
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:openshift:compatibility-requirements-events
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-compatibility-requirements-operator
  name: compatibility-requirements-controllers
