apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: compatibility-requirements-controllers
  namespace: openshift-compatibility-requirements-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-gate: "CRDCompatibilityRequirementOperator"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: compatibility-requirements-controllers
  unhealthyPodEvictionPolicy: AlwaysAllow
