apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - machine-api-machine-vap.yaml
  - machine-api-machine-set-vap.yaml
  - cluster-api-machine-vap.yaml
  - cluster-api-machine-set-vap.yaml
  - prevent-capi-fields-unsupported-by-mapi.yaml
  - only-create-mapi-machine-if-authoritative-api-capi.yaml
  - prevent-authoritative-mapi-machineset-create-when-capi-exists.yaml
  - validate-capi-machine-creation.yaml
  - validate-capi-machine-set-creation.yaml
  - prevent-migration-when-machine-updating.yaml
  - provide-warning-when-not-synchronized.yaml
  - authoritative-api-transition-requires-capi-infrastructure-ready.yaml
